version: '3.4'


services:


    # Main node user orchestration
    conductor:
      build: .
      image: "zelkova/c-node"
      container_name: conductor
      ports:
        - "5000:5000"
      environment:
      - URL_BASE
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      command: go run traffic.go
