version: '3'


services:

    # Computing node
    computing_node:
      build: .
      image: "zelkova/c-node"
      ports:
        - "5000:5000"
      environment:
      - URL_BASE
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - UNIQUE_ID
      # Placeholder while in development
      command: tail -F anything
