version: '2'



services:

  zelkova-apis:
    build: .
    image: "zelkova:apis"

    ports:
      - "7500:7500"
    command: gunicorn -w $GTH -b $URL_BASE:7500 access:app
    environment:
      - URL_BASE
      - REDIS_AUTH
