version: '2'

volumes:
  influxdb:


services:

  zelkova-apis:
    build: .
    image: "zelkova:apis"
    ports:
      - "7500:7500"
    command: ./startup.sh
    environment:
      - GTH
      - URL_BASE
      - INFLUXDB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD 
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD

  # Define an InfluxDB service
  influxdb:
    image: influxdb:latest
    volumes:
      - ./backup/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - INFLUXDB
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_READ_USER
      - INFLUXDB_READ_USER_PASSWORD 
      - INFLUXDB_WRITE_USER
      - INFLUXDB_WRITE_USER_PASSWORD

    command: "influxd"
